config/routes.rb
Luncheon::Application.routes.draw do
  
  post '/eshq/socket' => "stream#connect", :as => :stream

  get '/lunches/template' => "lunches#template", :as => :lunch_template #get lunch underscore template
  post '/lunches/:id/add' =>  "lunches#add",      :as => :add_to_lunch      #add user to lunch
  post '/lunches/:id/remove' => "lunches#remove", :as => :remove_from_lunch      #add user to lunch
  resources :lunches

  root :to => "main#index"

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
  attr_accessible :place, :start_time, :creator, :creator_name
  after_save :update_clients

  has_and_belongs_to_many :people
  validates_associated :people

  before_destroy :clear_records

  def clear_records
    self.people.clear
  end

  def update_clients
    ESHQ.send :channel => "lunch-channel", :data => self.to_json(:include => :people), :type => "message"
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :fb_id, :name

  validates_uniqueness_of :fb_id

  has_and_belongs_to_many :lunches

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def clearOldLunches
    Lunch.where('start_time <= ?', Time.zone.now.midnight).destroy_all
  end

end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  
  # GET /lunches/template.html
  def template
    render :text => File.read(Rails.root.join('app/views/lunches/_template.html'))
  end

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lunches.to_json(:include => :people) }
    end
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lunch }
    end
  end

  # GET /lunches/new
  # GET /lunches/new.json
  def new
    @lunch = Lunch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lunch }
    end
  end

  # GET /lunches/1/edit
  def edit
    @lunch = Lunch.find(params[:id])
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(params[:lunch])

    respond_to do |format|
      if @lunch.save
        ESHQ.send :channel => "lunch-notifications", :data => {:lunch => @lunch, :type => 'new'}.to_json, :type => "message"
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render json: @lunch, status: :created, location: @lunch }
      else
        format.html { render action: "new" }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lunches/1
  # PUT /lunches/1.json
  def update
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      if @lunch.update_attributes(params[:lunch])
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  #POST /lunches/1/add
  def add
    @lunch = Lunch.find(params[:id])
    @person = Person.find_or_create_by_fb_id_and_name(params[:user])
    @lunch.people << @person
    @lunch.save
    ESHQ.send :channel => "lunch-notifications", :data => {:lunch => @lunch, :person => @person, :type => 'add'}.to_json, :type => "message"
    render :nothing => true
  end

  #POST /lunches/1/remove
  def remove
    @lunch = Lunch.find(params[:id])
    @person = Person.find_by_fb_id(params[:user][:fb_id])
    @lunch.people.delete(@person)
    @lunch.save
    render :nothing => true
  end  

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch = Lunch.find(params[:id])
    @lunch.destroy

    respond_to do |format|
      format.html { redirect_to lunches_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @lunch = Lunch.new
    clearOldLunches()
  end
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController
  
  def connect
    socket = ESHQ.open :channel => params[:channel]
    render :json => {:socket => socket}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luncheon</title>
  <%= stylesheet_link_tag "application", params[:controller], :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>

  <div id="fb-root"></div>
  <script>
    //some global vars
    var fb_app_id = '<%= ENV['FB_APP_ID'] %>';

    //asynch loads
    (function() {
      var e = document.createElement('script');
      e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
      e.async = true;
      document.getElementById('fb-root').appendChild(e);
    }());
  </script>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js",
        "//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js",
        "//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js",
        "//app.eventsourcehq.com/es.js",
        "application",
         params[:controller] 
  %>
</body>
</html>

app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunches/edit.html.erb
<h1>Editing lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/index.html.erb
<h1>Listing lunches</h1>

<table>
  <tr>
    <th>Place</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lunches.each do |lunch| %>
  <tr>
    <td><%= lunch.place %></td>
    <td><%= link_to 'Show', lunch %></td>
    <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
    <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lunch', new_lunch_path %>

app/views/lunches/new.html.erb
<h1>New lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place:</b>
  <%= @lunch.place %>
</p>


<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>

app/views/main/index.html.erb
<h1>Agency Lunch</h1>
<a class="login_btn">connect to app</a>
<a target="_blank" href="/lunch_extension.zip" class="chrome hide">want instant notifications with chrome?</a>
<div id="lunches">
  <%= form_for(@lunch) do |f| %>
    <%= f.text_field :place, :placeholder => 'New Place' %>
    <div class="center datetime">
    <%= f.datetime_select :start_time, :discard_year => true, :ampm => true, :default => Time.zone.now, :datetime_separator => '<div class="clr"></div>', :use_month_numbers => true, :date_separator => '<div class="left">/</div>', :time_separator => '<div class="left">:</div>' %>
    </div>
    <%= f.submit :value => '+' %>
  <% end %>
</div>